version: "0.1"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
      - 3006:3000
  user:
    build: ./services/userService
    ports:
      - 3001:3001
  question:
    build: ./services/questionService
    ports:
      - 3002:3002
  matching:
    build: ./services/matchingService
    ports:
      - 3003:3003
    restart: unless-stopped
  database:
    build: ./services/database
    expose:
      - 3005:3005
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  producer:
    build: ./services/rabbitMQ
    ports:
      - 3009:3009